### ISSUE TITLE
File-based databases deleted on close

### ISSUE THREAD

**Issue by LucidToday** [stack/Restructure#1]
This package is nice, but I'm finding that it deletes file-based databases from the file system when the database is closed. This seems rather counter-intuitive, as most people I imagine would like their databases to stick around. I can see in the code where it does this, so it seems a deliberate feature... but maybe I misunderstand. Please advise.

**Comment by stack** [comment]
I know this is 3 years too late, but it turns out that:

1. I never used the `close` function in my applications. I just let the app terminate.
2. I had an explicit file delete in the `close` functions for reasons I don't understand.

Release 2.1.2 fixes this issue.

**Comment by LucidToday** [comment]
Thanks for fixing it.
